require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/todolists", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # TodoList. As you add validations to TodoList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TodoList.create! valid_attributes
      get todo_lists_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      todolist = TodoList.create! valid_attributes
      get todo_list_path(todolist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_todo_list_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      todolist = TodoList.create! valid_attributes
      get edit_todo_list_path(todolist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TodoList" do
        expect {
          post todo_lists_path, params: { todolist: valid_attributes }
        }.to change(TodoList, :count).by(1)
      end

      it "redirects to the created todolist" do
        post todo_lists_path, params: { todolist: valid_attributes }
        expect(response).to redirect_to(todo_list_path(TodoList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TodoList" do
        expect {
          post todo_lists_path, params: { todolist: invalid_attributes }
        }.to change(TodoList, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post todo_lists_path, params: { todolist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested todolist" do
        todolist = TodoList.create! valid_attributes
        patch todo_list_path(todolist), params: { todolist: new_attributes }
        todolist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the todolist" do
        todolist = TodoList.create! valid_attributes
        patch todo_list_path(todolist), params: { todolist: new_attributes }
        todolist.reload
        expect(response).to redirect_to(todo_list_path(todolist))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        todolist = TodoList.create! valid_attributes
        patch todo_list_path(todolist), params: { todolist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested todolist" do
      todolist = TodoList.create! valid_attributes
      expect {
        delete todo_list_path(todolist)
      }.to change(TodoList, :count).by(-1)
    end

    it "redirects to the todolists list" do
      todolist = TodoList.create! valid_attributes
      delete todo_list_path(todolist)
      expect(response).to redirect_to(todo_lists_path)
    end
  end
end
